name: XP to Emerald
main: com.scott_weldon.xp_to_emerald.XPtoEmerald
version: 0.0.19
commands:
  xptoemerald:
    description: Convert some XP to Emeralds.
    usage: "usage: /<command> [xp amount]"
    permissions: xptoemerald.convert
  emeraldtoxp:
    description: Convert some Emeralds to XP.
    usage: "usage: /<command> [emerald amount]"
    permissions: xptoemerald.convert
permissions:
  xptoemerald.*:
    description: Give access to all XPtoEmerald commands.
    children:
      xptoemerald.convert: true
      xptoemerald.admin: true
  xptoemerald.convert:
    description: Allow converting XP to Emeralds and back.
    default: true
  xptoemerald.admin:
    description: Allow converting of other players' resources.
    children:
      xptoemerald.convert: true
    default: op
    