name: XP to Emerald
main: com.scott_weldon.xp_to_emerald.XPtoEmerald
version: 1.1-dev
commands:
  xptoemerald:
    description: Convert some XP to Emeralds.
    usage: "usage: /<command> [player] [xp amount]"
    permissions: xptoemerald.convert
  emeraldtoxp:
    description: Convert some Emeralds to XP.
    usage: "usage: /<command> [player] [emerald amount]"
    permissions: xptoemerald.convert
  xp2em:
    description: Alias of xptoemerald.
    usage: "usage: /<command> [player] [xp amount]"
    permissions: xptoemerald.convert
  em2xp:
    description: Alias of emeraldtoxp.
    usage: "usage: /<command> [player] [emerald amount]"
    permissions: xptoemerald.convert
permissions:
  xptoemerald.*:
    description: Give access to all XPtoEmerald commands.
    default: op
    children:
      xptoemerald.convert: true
      xptoemerald.admin: true
      xptoemerald.sign: true
  xptoemerald.convert:
    description: Allow converting of XP to Emeralds and back via commands.
    default: true
  xptoemerald.sign:
    description: Allow conversion via signs.
    default: true
  xptoemerald.admin:
    description: Allow converting of other players' resources.
    default: op